import { Header } from '@/components/Header'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ 
  subsets: ['latin'],
  preload: true,
  weight: ['300', '400', '500', '600', '700', '800'],
  fallback: ['Poppins']
})

export const metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${montserrat.className} bg-background`}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
